Create, Import, and Archive/Reactivate Projects
sillsdev/appbuilder-portal pull request #1059
Opened 2024-12-05 15:31 UTC by FyreByrd

Added jobs to handle creation of projects in BuildEngine.
Handle Project Imports.
I am not 100% certain what the full expected behavior is for Archival and Reactivation, so we will need to discuss this before merging.

Add Project Page:
![image](https://github.com/user-attachments/assets/97a6ea9e-e161-4d55-abcc-6f031cfcdefb)

![image](https://github.com/user-attachments/assets/9f6fee24-f56d-4ae8-848b-ab2a90a604de)

Import Project Page:
![image](https://github.com/user-attachments/assets/3765643f-62bc-42e8-a870-8902179a4fb3)

![image](https://github.com/user-attachments/assets/5d3a01e7-cd89-4015-8310-72a295cf8a59)

2024-12-12 18:56 UTC, chrisvire commented
When a project is first created:

![image](https://github.com/user-attachments/assets/c2707fd5-5ba5-4144-9ce7-dd44a16ccb71)

2024-12-12 19:04 UTC, FyreByrd commented
> When a project is first created:
> 
> ![image](https://private-user-images.githubusercontent.com/517814/395293115-c2707fd5-5ba5-4144-9ce7-dd44a16ccb71.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQwMzAxMjAsIm5iZiI6MTczNDAyOTgyMCwicGF0aCI6Ii81MTc4MTQvMzk1MjkzMTE1LWMyNzA3ZmQ1LTViYTUtNDE0NC05Y2U3LWRkNDRhMTZjY2I3MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxMlQxODU3MDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wY2UwZjNmM2Y4M2Q3ZWUzMDE5MjU2NTdjYjI5NWE3YTc3N2VjZDcxY2ExNTIyM2VmZmNiYzE1Njg2ZjFhN2NiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.1-VS1qoro9TQ56RueSXEAWzz19IzBsUAlOdubKLVy_k)

Taken care of

2024-12-13 16:28 UTC, chrisvire commented
## Add Project
User Experience issues:
* I accidentally hit enter when the Save button didn't have focus and the project was created. I was surprised by this. This is not the behavior of S1.
* In S1, the save button is disabled until all the required fields (Project Name, Language Code ... and I assume Project Group and Type, but they have default values) are filled in.
* In S2. the only option is "Scripture App Builder" but it should have all the options (in table Application Types)
* In S2, the fields should stack all vertically if on a narrow device

I noticed on the Add Project page that the breakpoint for switching to a narrow layout is 380px. That is not one of the default breakpoints in Tailwind. Curious about it. The breakpoint in S2 is 640 (sm breakpoint).

## Import Project
User Experience issues:
* In S2. the only option is "Scripture App Builder" but it should have all the options (in table Application Types)
* I selected a file and clicked save, but nothing happened.

2024-12-13 16:29 UTC, chrisvire requested changes
User experience issues

2024-12-13 17:55 UTC, FyreByrd commented
> * In S2. the only option is "Scripture App Builder" but it should have all the options (in table Application Types)

Regarding the available Application Types, I am only presenting the available options based on the `OrganizationProductDefinitions` table. My assumption was that we wouldn't want for users to create a project that isn't valid for their organization. In the example data for dev, all of the entries in `OrganizationProductDefinitions` for SIL have product definitions that use the SAB Application Type, hence SAB is the only option that will be visible.

2024-12-13 19:12 UTC, FyreByrd commented
> > * In S2. the only option is "Scripture App Builder" but it should have all the options (in table Application Types)
> 
> Regarding the available Application Types, I am only presenting the available options based on the `OrganizationProductDefinitions` table. My assumption was that we wouldn't want for users to create a project that isn't valid for their organization. In the example data for dev, all of the entries in `OrganizationProductDefinitions` for SIL have product definitions that use the SAB Application Type, hence SAB is the only option that will be visible.

This is incorrect behavior and has been updated to show all application types

2024-12-13 22:18 UTC, FyreByrd commented
> * I accidentally hit enter when the Save button didn't have focus and the project was created. I was surprised by this. This is not the behavior of S1.

I have resolved all the issues except this one. As best as I can tell, this is the default behavior of the browser. This would likely need to be fixed in multiple location, not just the add project form.
For now, I think the issue has been partially mitigated by blocking form submission unless the name and language code are both set.

2025-01-15 13:53 UTC, chrisvire commented
> > * I accidentally hit enter when the Save button didn't have focus and the project was created. I was surprised by this. This is not the behavior of S1.
> 
> I have resolved all the issues except this one. As best as I can tell, this is the default behavior of the browser. This would likely need to be fixed in multiple location, not just the add project form. For now, I think the issue has been partially mitigated by blocking form submission unless the name and language code are both set.

I think my major concern was that the save button was enabled when the required fields were not all filled out.

2025-01-15 14:04 UTC, FyreByrd commented
> > > * I accidentally hit enter when the Save button didn't have focus and the project was created. I was surprised by this. This is not the behavior of S1.
> > 
> > 
> > I have resolved all the issues except this one. As best as I can tell, this is the default behavior of the browser. This would likely need to be fixed in multiple location, not just the add project form. For now, I think the issue has been partially mitigated by blocking form submission unless the name and language code are both set.
> 
> I think my major concern was that the save button was enabled when the required fields were not all filled out.

In that case the issue should be fixed by https://github.com/sillsdev/appbuilder-portal/pull/1059/commits/2021603abb81dd3f28074fc00d1a3cfb9a955394

2025-01-15 16:07 UTC, chrisvire requested changes
## Add Project
User Experience issues:
1. The Add Products button should be disabled until the repository location is available.

## Import Project
User Experience issues:
1. I selected a group, type, and chose a file, but the save button was disabled so I couldn't do anything.

![image](https://github.com/user-attachments/assets/e14f7f8f-8f7d-45c8-a0fe-1302ea104890)

2025-01-15 20:06 UTC, FyreByrd commented
> ## Import Project
> User Experience issues:
> 
> 1. I selected a group, type, and chose a file, but the save button was disabled so I couldn't do anything.
> 
> ![image](https://private-user-images.githubusercontent.com/517814/403493475-e14f7f8f-8f7d-45c8-a0fe-1302ea104890.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzY5NzE4MDgsIm5iZiI6MTczNjk3MTUwOCwicGF0aCI6Ii81MTc4MTQvNDAzNDkzNDc1LWUxNGY3ZjhmLThmN2QtNDVjOC1hMGZlLTEzMDJlYTEwNDg5MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMTE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDExNVQyMDA1MDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMzU1ZDgzZDlmNDZkOWE3YmRlMjc4OWM1ZDMwM2Y0MGViZTdjNTIwOGJlYzQyZTgzMTQ1ZTU1NmE0ZmVkYTNhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.vY6G8gj3lxtHQwLieTCCIpXt9MV1hroyv8F10dU-4KE)

I was unable to reproduce this issue. I am fairly certain that it should be showing some error messages if it is in a state that would block submission.

2025-01-28 17:44 UTC, FyreByrd commented
Added kebab menus to both the projects list and the individual project view:

![image](https://github.com/user-attachments/assets/54184e2a-ed96-47d2-80a5-c7614877e6fb)

![image](https://github.com/user-attachments/assets/dadd236c-4167-46d0-ae84-eb5ab2a26eb5)

2025-01-30 15:19 UTC, merged